apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-playground
  namespace: {{ .Values.namespace }}
  labels:
    app: llamastack-playground
spec:
  to:
    kind: Service
    name: llamastack-playground
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
