apiVersion: v1
kind: Service
metadata:
  name: llamastack-playground
  namespace: {{ .Values.namespace }}
  labels:
    app: llamastack-playground
spec:
  selector:
    app: llamastack-playground
  ports:
    - port: 8501
      targetPort: 8501
      name: http
